#!/usr/bin/env python3
"""
命令行字体转换工具 - 将TTF字体转换为Retro-Go格式
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

# 默认字体 - 使用系统中文字体
DEFAULT_FONT = "NotoSansCJK-Regular.ttc"
# 备选字体
ALTERNATE_FONTS = [
    "WenQuanYi Micro Hei.ttf",
    "NotoSansCJKsc-Regular.otf",
    "SimSun.ttf",
    "SimHei.ttf",
]

def find_chinese_font():
    """查找可用的中文字体"""
    # 常见的字体目录
    font_dirs = [
        "/usr/share/fonts/truetype/noto/",
        "/usr/share/fonts/noto/",
        "/usr/share/fonts/opentype/noto/",
        "/usr/share/fonts/wenquanyi/",
        "/usr/share/fonts/opentype/",
        "/usr/share/fonts/truetype/",
        "/usr/share/fonts/",
        "/Library/Fonts/",
        "C:\\Windows\\Fonts\\",
    ]

    for font_dir in font_dirs:
        if not os.path.exists(font_dir):
            continue
        for font_file in os.listdir(font_dir):
            font_path = os.path.join(font_dir, font_file)
            if any(name in font_file for name in ["NotoSansCJK", "WenQuan", "Sim", "Hei"]):
                try:
                    ImageFont.truetype(font_path, 12)
                    return font_path
                except Exception:
                    continue
    return None

def convert_char(font, char_code):
    """
    转换单个字符为位图
    返回: (width, height, x_offset, y_offset, x_delta, bitmap_data)
    """
    try:
        char = chr(char_code)
    except ValueError:
        return None

    # 获取字符尺寸
    bbox = font.getbbox(char)
    if not bbox:
        return None

    # 调整大小以确保对齐
    left, top, right, bottom = bbox
    width = right - left
    height = bottom - top

    # 创建图像并绘制字符
    img = Image.new('1', (width, height), color=1)
    draw = ImageDraw.Draw(img)
    draw.text((-left, -top), char, font=font, fill=0)

    # 获取像素数据
    pixels = list(img.getdata())

    # 转换为位流
    bitmap_data = []
    for y in range(height):
        byte_val = 0
        bit_pos = 0
        for x in range(width):
            pixel = pixels[y * width + x]
            if pixel == 0:  # 黑色是字体
                byte_val |= (1 << (7 - bit_pos))
            bit_pos += 1
            if bit_pos == 8:
                bitmap_data.append(byte_val)
                byte_val = 0
                bit_pos = 0
        if bit_pos > 0:
            bitmap_data.append(byte_val)

    # 计算各种偏移和尺寸
    # 简化版，让Retro-Go能正常显示
    y_offset = -top
    x_offset = -left
    x_delta = width + 1  # 稍微加一点间距

    return (width, height, x_offset, y_offset, x_delta, bitmap_data)

def convert_font(font_path, char_ranges, font_size=12):
    """转换TTF字体为Retro-Go格式"""

    # 加载字体
    try:
        font = ImageFont.truetype(font_path, font_size)
    except Exception as e:
        print(f"无法加载字体 {font_path}: {e}")
        sys.exit(1)

    # 解析字符范围
    chars_to_convert = []
    for rng in char_ranges.split(','):
        rng = rng.strip()
        if '-' in rng:
            start, end = rng.split('-')
            chars_to_convert.extend(range(int(start), int(end)+1))
        else:
            chars_to_convert.append(int(rng))

    # 转换字符
    glyphs = []
    total = len(chars_to_convert)
    for i, char_code in enumerate(chars_to_convert):
        if (i+1) % 20 == 0:
            print(f"转换进度: {i+1}/{total}")

        result = convert_char(font, char_code)
        if result:
            width, height, x_off, y_off, x_delta, bitmap = result
            glyphs.append((char_code, width, height, x_off, y_off, x_delta, bitmap))

    # 生成C数组
    return generate_c_code(glyphs, font_size)

def generate_c_code(glyphs, font_size):
    """生成C代码"""
    lines = []

    # 字体名称
    font_name = f"font_Chinese{font_size}"

    # 生成位图数据
    lines.append(f"// {font_name}")
    lines.append("// Generated by font_converter_cli.py")
    lines.append("")

    # 计算总大小
    total_size = 0
    for char_code, width, height, x_off, y_off, x_delta, bitmap in glyphs:
        total_size += len(bitmap)

    lines.append(f"// Total glyphs: {len(glyphs)}")
    lines.append(f"// Total bitmap size: {total_size} bytes")
    lines.append("")

    # 生成位图数据
    lines.append("static const uint8_t glyph_bitmap[] = {")
    bitmap_offset = 0
    glyph_info = []
    for char_code, width, height, x_off, y_off, x_delta, bitmap in glyphs:
        # 保存偏移信息
        glyph_info.append((char_code, width, height, x_off, y_off, x_delta, bitmap_offset))
        bitmap_offset += len(bitmap)

        # 输出位图数据
        line = f"    /* 0x{char_code:04X} '{chr(char_code)}' */ "
        line += ", ".join(f"0x{b:02X}" for b in bitmap)
        lines.append(line + ",")
    lines.append("};")
    lines.append("")

    # 生成字形信息
    lines.append("static const uint8_t glyph_data[] = {")
    for char_code, width, height, x_off, y_off, x_delta, offset in glyph_info:
        # 打包为 rg_font_glyph_t 格式
        #  struct {
        #      uint16_t code;
        #      uint8_t yOffset;
        #      uint8_t width;
        #      uint8_t height;
        #      uint8_t xOffset;
        #      uint8_t xDelta;
        #      uint8_t data[]; (指定位图数据偏移)
        #  }
        # 实际上我们简化处理
        line = f"    0x{(char_code & 0xFF):02X}, 0x{(char_code >> 8) & 0xFF},"
        line += f" {y_off:3d}, {width:3d}, {height:3d}, {x_off:3d}, {x_delta:3d},"
        line += f" 0x{(offset & 0xFF):02X}, 0x{(offset >> 8) & 0xFF},"
        lines.append(line)

    # 结束标记
    lines.append("    0x00, 0x00, 0, 0, 0, 0, 0, 0")
    lines.append("};")
    lines.append("")

    # 生成字体结构体
    lines.append(f"const rg_font_t {font_name} = {{")
    lines.append(f'    .name = "Chinese{font_size}",')
    lines.append(f'    .type = 0,  // proportional')
    lines.append(f'    .width = {font_size},')
    lines.append(f'    .height = {font_size},')
    lines.append(f'    .chars = {len(glyphs)},')
    lines.append("    .data = (uint8_t*)&glyph_data,")
    lines.append("};")

    return "\n".join(lines)

def main():
    import argparse

    parser = argparse.ArgumentParser(description="TTF字体到Retro-Go字体转换器")
    parser.add_argument("-f", "--font", help="TTF字体文件路径")
    parser.add_argument("-s", "--size", type=int, default=12, help="字体大小")
    parser.add_argument("-r", "--ranges", required=True, help="字符范围 (例如: '32-126,19968-40869')")
    parser.add_argument("-o", "--output", help="输出文件")

    args = parser.parse_args()

    # 查找字体
    font_path = args.font or find_chinese_font()
    if not font_path:
        print("无法找到中文字体，请使用 -f 参数指定字体路径")
        sys.exit(1)

    print(f"使用字体: {font_path}")

    # 转换字体
    c_code = convert_font(font_path, args.ranges, args.size)

    # 输出
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(c_code)
        print(f"已保存到 {args.output}")
    else:
        print(c_code)

if __name__ == '__main__':
    main()
